# Setup workflow to test code using pytest and poetry
name: Test
on : 
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Setup the environment
      # This moves the correct test files for the big tests, and the config file
        run: |
          mv tests/data/full_data_expenses_wf.csv tests/data/full_data_expenses.csv
          mv tests/data/full_data_sales_wf.csv tests/data/full_data_income.
          mv config_example.yml config.yml
      - name: Test with pytest
        run: poetry run pytest tests